enum EChannel {
	SELECT_FOLDER = 'SELECT_FOLDER',
	SELECT_MULTIPLE_FILES = 'SELECT_MULTIPLE_FILES',
	STEAM_GRID_REQUEST = 'STEAM_GRID_REQUEST',
	DOWNLOAD_ASSET = 'DOWNLOAD_ASSET',
	PLATFORM = 'PLATFORM',
	AUTO_UPDATER = 'AUTO_UPDATER',
	FETCH_STEAM_USER_COLLECTIONS = 'FETCH_STEAM_USER_COLLECTIONS',
	SAVE_STEAM_COLLECTION = 'SAVE_STEAM_COLLECTION',
	IS_STEAM_CATEGORIES_READY = 'IS_STEAM_CATEGORIES_READY'
}

export default EChannel
